const plans = [
  {
    type: "FREE",
    currency: "naira",
    currencySymbol: "₦",
    price: 0,
    features: [
      "Up to 10 images allowed",
      "Free Ad",
      "Keep online for 180 days",
    ],
  },
  {
    type: "Urgent",
    currency: "naira",
    currencySymbol: "₦",
    price: 35000,
    features: [
      "30 days of promotion",
      "Facebook Ads (7 days)",
      "Google Ads (7 days)",
      "Up to 10 images allowed",
      "Urgent - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
  {
    type: "Urgent",
    currency: "dollar",
    currencySymbol: "$",
    price: 100,
    features: [
      "30 days of promotion",
      "Facebook Ads (7 days)",
      "Google Ads (7 days)",
      "Up to 10 images allowed",
      "Urgent - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
  {
    type: "Premium",
    currency: "naira",
    currencySymbol: "₦",
    price: 55000,
    features: [
      "60 days of promotion",
      "Facebook Ads (14 days)",
      "Google Ads (14 days)",
      "Up to 12 images allowed",
      "Top Ads - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
  {
    type: "Premium",
    currency: "dollar",
    currencySymbol: "$",
    price: 145,
    features: [
      "60 days of promotion",
      "Facebook Ads (14 days)",
      "Google Ads (14 days)",
      "Up to 12 images allowed",
      "Top Ads - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
  {
    type: "Premium+",
    currency: "naira",
    currencySymbol: "₦",
    price: 75000,
    highlight: {
        header:"#028e7b",
        headerColor:"#fff",
        button:"#EA280A",
        buttonColor:"#FFF"
    },
    features: [
      "120 days of promotion",
      "Facebook Ads (30 days)",
      "Google Ads (30 days)",
      "Up to 15 images allowed",
      "Featured Ads - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
  {
    type: "Premium+",
    currency: "dollar",
    currencySymbol: "$",
    price: 200,
    features: [
      "120 days of promotion",
      "Facebook Ads (30 days)",
      "Google Ads (30 days)",
      "Up to 15 images allowed",
      "Featured Ads - NGN (₦)",
      "Keep online for 365 days",
    ],
  },
];

export default plans;
